### ISSUE TITLE
BlogPostsTable missing

### ISSUE THREAD

**Issue by ronaldoviber** [archey347/userfrosting-blog#1]
after  "php bakery migrate"

Unable to find the migration class '\UserFrosting\Sprinkle\Blog\Database\Mi
  grations\v000\BlogPostsTable'

**Comment by archey347** [comment]
@ronaldoviber  I have tried to recreate the problem by doing a fresh install of the sprinkle but it seemed to work ok.

Is that an error that is being raised when you are running `php bakery migrate` or did it come up when you tried to open it in the browser?

Another thing to check is to make sure that the folder the sprinkle is sat in is called `blog` not `userfrosting-blog`

**Comment by obe711** [comment]
I received the same error.
In Migrator.php line 340:
                                                                                                          
  Unable to find the migration class '\UserFrosting\Sprinkle\Blog\Database\Migrations\v000\BlogPostsTabl  
  e'.

**Comment by archey347** [comment]
The issue I have is that I can't seem to replicate the issue for some reason. I'll try and load it in a fresh install of userfrosting in a fresh VM.

**Comment by archey347** [comment]
Turns out I missed a step in the sprinkle installation instructions. Before you run the `php bakery migrate` command, you need to run the `composer update` to update all of the namespaces.

There were also a few other errors which cropped up, but I've also sorted them.

**Comment by obe711** [comment]
@archey347 I just tried again. I updated the laravel/homestead box to 6.0.0, then installed a new copy of Userfrosting. I Cloned the sprinkle to the "blog" directory, edited sprinkles.json then ran Composer Update. Then when I ran php bakery migrate I got this message:

 Migrating \UserFrosting\Sprinkle\Blog\Database\Migrations\v000\CustomPermissions...
In Connection.php line 647:
                                                                               
  SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column  
   'permission_id' at row 1 (SQL: insert into `permission_roles` (`created_at  
  `, `permission_id`, `role_id`, `updated_at`) values (2018-05-12 04:57:47, ,  
   2, 2018-05-12 04:57:47))                                                    
                                                                               

In PDOStatement.php line 143:
                                                                               
  SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column  
   'permission_id' at row 1                                                    
                                                                               

In PDOStatement.php line 141:
                                                                               
  SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column  
   'permission_id' at row 1                                                    
                                                                               

migrate [-p|--pretend]

**Comment by archey347** [comment]
I can't seem to replicate this error, however I'm not using homestead.

The error you gave me comes from when the permissions are linked with a role, and looking at the error suggests that the `permission_id` is not being sent. I have tried to run the command which links the permission and the role with a non integer value as the permission id, but there is no error.

What environment are you running using (OS, PHP version and database software)?

**Comment by obe711** [comment]
Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-116-generic x86_64)
PHP 7.2.3-1
MySQL 5.7.21-0

**Comment by archey347** [comment]
@obe711 I think I've fixed the issue. It was specific to MySQL but not MariaDB. It was only until I switched to MySQL the error came up.
